# Generated by Django 6.0 on 2025-12-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_size',
            field=models.CharField(choices=[('large', 'Large'), ('regular', 'Regular')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
