# Generated by Django 6.0 on 2026-01-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, help_text='Rating from 1.0 to 5.0', max_digits=2),
        ),
    ]
